version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - cloud_storage:/home/abdulrahman/cloud_uploads
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clouddb
      - DB_USER=clouduser
      - DB_PASSWORD=cloudpassword
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpassword
      POSTGRES_DB: clouddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql  # ← removed /data

volumes:
  cloud_storage:
  pgdata: